window.Editor={
canvas:null, scale:1, drag:null, offx:0, offy:0, snap:false, selectedIdx:null,
init(){this.canvas=document.getElementById('editor-canvas-wrapper');document.addEventListener('mousemove',e=>this._onMove(e));document.addEventListener('mouseup',e=>this._onUp(e));},
_onMove(e){if(!this.drag)return;const rect=this.canvas.getBoundingClientRect();let x=(e.pageX-rect.left-this.offx)/this.scale;let y=(e.pageY-rect.top-this.offy)/this.scale;if(this.snap){const g=8;x=Math.round(x/g)*g;y=Math.round(y/g)*g;}this.drag.style.left=x+'px';this.drag.style.top=y+'px';},
_onUp(e){if(this.drag){const idx=this.drag.dataset.idx;if(currentProject && typeof idx!=='undefined'){currentProject.items[idx].left=parseFloat(this.drag.style.left)||0;currentProject.items[idx].top=parseFloat(this.drag.style.top)||0;persistCurrentProject();}}this.drag=null;},
addItem(type='text'){if(!currentProject)return alert('Open or create project first');const it={id:genId('it'),type:type,text:type==='text'?'Text':type==='button'?'Button':'Image',left:40,top:40,width:120,height:40,color:'#111',bg:'#fff'};currentProject.items.push(it);persistCurrentProject();renderCanvasItems();},
renderCanvas(elemId='editor-canvas-wrapper'){this.canvas=document.getElementById(elemId);this.canvas.innerHTML='';if(!currentProject||!currentProject.items)return;currentProject.items.forEach((it,idx)=>{const d=document.createElement('div');d.className='editor-item';d.dataset.idx=idx;d.style.left=(it.left||0)+'px';d.style.top=(it.top||0)+'px';d.style.width=(it.width||120)+'px';d.style.height=(it.height||40)+'px';d.style.color=it.color||'#111';d.style.background=it.bg||'#fff';if(it.type==='button')d.innerHTML='<button style="width:100%;height:100%">'+(it.text||'Button')+'</button>';else if(it.type==='image')d.innerHTML='<img src="'+(it.src||'')+'" style="max-width:100%;height:100%"/>';else d.textContent=it.text||'Text';d.onmousedown=(e)=>{this.drag=d;this.offx=e.offsetX;this.offy=e.offsetY;selectItemByIdx(idx);};this.canvas.appendChild(d);});},
zoomIn(){this.scale=+(this.scale+0.1).toFixed(2);this.applyScale();},
zoomOut(){this.scale=Math.max(0.3,+(this.scale-0.1).toFixed(2));this.applyScale();},
applyScale(){this.canvas.style.transform='scale('+this.scale+')';},
toggleSnap(){this.snap=!this.snap;document.getElementById('snapBtn').textContent=this.snap?'Snap: ON':'Snap: OFF';},
duplicateSelected(){if(this.selectedIdx===null)return;const it=JSON.parse(JSON.stringify(currentProject.items[this.selectedIdx]));it.id=genId('it');it.left+=20;it.top+=20;currentProject.items.push(it);persistCurrentProject();renderCanvasItems();},
deleteSelected(){if(this.selectedIdx===null)return;if(!confirm('Delete item?'))return;currentProject.items.splice(this.selectedIdx,1);persistCurrentProject();renderCanvasItems();hideInspector();},
publishProject(){if(!currentProject)return alert('Open project first');if(!currentProject.published)currentProject.published={urlId:genId('share'),date:Date.now()};persistCurrentProject();const url=window.location.href.split('?')[0]+'?share='+currentProject.published.urlId;prompt('Published! Share this link:',url);},
exportProjectAsHTML(){if(!currentProject)return alert('Open project first');const title=currentProject.name||'project';const itemsHtml=(currentProject.items||[]).map(it=>{if(it.type==='button')return`<div style="position:absolute;left:${it.left}px;top:${it.top}px;width:${it.width}px;height:${it.height}px">${it.text}</div>`; if(it.type==='image')return`<img src="${it.src||''}" style="position:absolute;left:${it.left}px;top:${it.top}px;width:${it.width}px;height:${it.height}px"/>`;return`<div style="position:absolute;left:${it.left}px;top:${it.top}px">${it.text}</div>`;}).join('\n'); const html=`<!doctype html><html><head><meta charset="utf-8"><title>${title}</title><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div style="position:relative;width:375px;height:667px;border:1px solid #ddd">${itemsHtml}</div></body></html>`;downloadBlob((title||'project')+'.html',html,'text/html');}
};
function renderCanvasItems(){Editor.renderCanvas();}
